# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd0add0878237e2f8e4dc11b01f1d4f85ad37082e69d9550d1142fac394ea83edf0bdb0c2c53677737b24d83d912614853a70165718ee42fc8c1c92d50d05b64

test:
  secret_key_base: 52a8f4c1cf6053b2ce8315a1c8d419bcf161550e8aa7406bcf1646372db400649f2366bc96dd0d9cef201e4998dfa16088bd21fd8b8a062d5414204fc49915fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
